repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/WGUNDERWOOD/tex-fmt
    rev: v0.5.7
    hooks:
      - id: tex-fmt
