repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.24.4
    hooks:
      - id: latexindent
